/// Divergence guard for the shipped emoji catalog.
///
/// `web/assets/catalog/emoji.json` is generated by
/// `tool/extract_emoji_catalog.dart` from the plugin's
/// `defaults/emoji/*.json`. This test rebuilds the expected entries straight
/// from the plugin tree (path-repointed like `preview_templates_test.dart`
/// pins the preview cards) and fails when either side drifts — the fix is to
/// re-run the tool, never to hand-edit the asset.
library;

import 'dart:convert';
import 'dart:io';

import 'package:gloss_editor/model/model.dart';
import 'package:gloss_editor/services/catalogs.dart';
import 'package:gloss_editor/logic/gloss_text.dart';
import 'package:test/test.dart';

import 'support/gloss_repository.dart';

final String _pluginDefaults = glossRepositoryFilePath(
  'src/main/resources/defaults/emoji',
);
const String _asset = 'web/assets/catalog/emoji.json';

void main() {
  test('the shipped catalog matches the plugin defaults, entry for entry', () {
    final Directory defaults = Directory(_pluginDefaults);
    expect(defaults.existsSync(), isTrue);

    final Map<String, GlossEmojiDoc> expected = <String, GlossEmojiDoc>{};
    for (final FileSystemEntity entity in defaults.listSync()) {
      if (entity is! File || !entity.path.endsWith('.json')) continue;
      final String name = entity.uri.pathSegments.last.replaceFirst(
        RegExp(r'\.json$'),
        '',
      );
      expected[name] = decodeGlossEmojiDoc(entity.readAsStringSync());
    }
    expect(expected, isNotEmpty);

    final Object? decoded = jsonDecode(File(_asset).readAsStringSync());
    final List<Object?> raw =
        (decoded! as Map<String, Object?>)['emoji']! as List<Object?>;
    expect(
      raw.length,
      expected.length,
      reason: 'entry count must match the defaults directory',
    );

    final List<String> sortedNames = expected.keys.toList()..sort();
    for (int index = 0; index < raw.length; index++) {
      final Map<String, Object?> entry = raw[index]! as Map<String, Object?>;
      final String name = entry['name']! as String;
      expect(name, sortedNames[index], reason: 'catalog is sorted by name');
      final GlossEmojiDoc doc = expected[name]!;
      expect(entry['trigger'], doc.trigger, reason: name);
      expect(entry['glyph'], doc.resolvedGlyph, reason: name);
      expect(entry['enabled'], doc.enabled, reason: name);
    }
  });

  test('the parser reads the shipped catalog back losslessly', () {
    final List<GlossEmojiEntry> entries = HuiCatalogs.parseEmoji(
      File(_asset).readAsStringSync(),
    );
    expect(entries, hasLength(67));
    final GlossEmojiEntry heart = entries.firstWhere(
      (GlossEmojiEntry entry) => entry.id == 'heart',
    );
    expect(heart.trigger, '<3');
    expect(heart.glyph, '❤');
    expect(heart.enabled, isTrue);
    expect(heart.fromWorkspace, isFalse);
    // Sorted like EmojiService.rebuild.
    final List<String> ids = <String>[
      for (final GlossEmojiEntry entry in entries) entry.id,
    ];
    final List<String> sorted = List<String>.of(ids)..sort();
    expect(ids, sorted);
  });
}
